[boot-settings]
boot-image = "graphics/hardcoded/hardcoded-30-4.png"
boot-sound = "_OST/_Sound Effects/bootscreen.ogg"
window-title = "Super Mario All-Stars++"

[episode-settings]
# We're using a custom life system, but the vanilla system still exists, so disable this ability
# This also makes the old code we used to prevent game overs obsolete
decrease-lives-after-death = false
# Set this true to have an easier powerdown ability
# This makes anotherPowerDownLibrary obsolete
easier-powerdown = false