[background2]
; Name that will appear in the editor
name = "SMB3 Clouds"
; Backdrop fill color
fill-color = 0x0091E0


; Add layers here, for example:

[Layer1]
depth = 300
speedX = -0.6
img = "clouds-top.png"
repeatX = true
alignY = TOP

[Layer2]
depth = 300
speedX = -0.6
img = "clouds-bottom.png"
repeatX = true
alignY = BOTTOM
