[background2]
; Name that will appear in the editor
name = "SMB3 Blocks"
; Backdrop fill color
fill-color = black


; Add layers here, for example:

[Layer1]
depth = 600
alignY = BOTTOM
img = "background2-1.png"
repeatX = true
fitY = true

[Layer2]
depth = 600
alignY = BOTTOM
img = "background2-1-bg2.png"
repeatX = true
repeatY = true
