[background2]
; Name that will appear in the editor
name = "SMW Clouds"
; Backdrop fill color
fill-color = black


; Add layers here, for example:

[Layer1]
depth = INFINITE
img = "background2-31.png"
repeatX = true
alignY = BOTTOM
frames=4
frameSpeed=4
