[background2]
; Name that will appear in the editor
name = "SMB2 Clouds"
; Backdrop fill color
fill-color = black


; Add layers here, for example:

[Layer1]
depth = 450
img = "background2-48.png"
repeatX = true
alignY = BOTTOM

[Layer2]
depth = 450
img = "background-751.png"
repeatX = true
alignY = BOTTOM
speedX = -0.5
priority = -20
