[background2]
; Name that will appear in the editor
name = "SMW Trees"
; Backdrop fill color
fill-color = black


; Add layers here, for example:

[Layer1]
depth = INFINITE
img = "background2-12-clouds1.png"
repeatX = true
repeatY = true
speedY = -15
priority = -98